services:

  proxy:
    image: nginx:latest
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      web:
        condition: service_healthy
    networks:
      - app_network

  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    restart: always
    env_file:
      - .env
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - app_network

  database:
    image: postgres:latest
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - app_network

  alembic:
    image: python:3.9
    container_name: alembic_container
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - .:/app
    working_dir: /app
    env_file:
      - .env
    networks:
      - app_network
    command: >
      sh -c "
      python -m venv /opt/venv &&
      /opt/venv/bin/pip install --upgrade pip &&
      /opt/venv/bin/pip install psycopg2 sqlalchemy alembic python-dotenv &&
      /opt/venv/bin/alembic upgrade head &&
      echo 'Migrations completed successfully!' &&
      exit 0
      "
    restart: "no"

  redis:
    image: redis:latest
    expose:
      - "6379"
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
