"""Add is_confirmed column to notes

Revision ID: 2ec253cefd5c
Revises: dd01fa04ce03
Create Date: 2025-01-15 13:37:17.623265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ec253cefd5c'
down_revision: Union[str, None] = 'dd01fa04ce03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('is_confirmed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'is_confirmed')
    # ### end Alembic commands ###
